### ISSUE TITLE
about rotations.h5

### ISSUE THREAD

**Issue by touchthefish233** [brown-ivl/Cafi-Net#2]
Hello, your work is very interesting, I would like to ask, is the code function corresponding to the evaluation index the run_metrics function in trainers/Canonical_fields_trainer.py? Can you provide the file rotation_file of the rotation matrix: "/home2/ragaram/rotation_file/rotations.h5"? Thank you so much!

**Comment by rohithagaram** [comment]
[rotations.zip](https://github.com/brown-ivl/Cafi-Net/files/14040532/rotations.zip)
@touchthefish233 zip contains the rotations.h files
